drop table if exists hashset;
drop table if exists categorytable;
drop table if exists categorydefinitions;
drop table if exists categorizeditemsdigest;
drop table if exists externalsource;

-- FIVES tables as per document "Fives Design Specification, PostgreSQL Digest Module", dd 2010-10-12

create table externalsource (
  sourceid integer,
  sourcecountry varchar(64) null,
  sourceindividual varchar(64) null,
  sourcedata varchar(64) null,
  sourceorg varchar(64) not null,
  PRIMARY KEY (sourceid)
);

create table categorizeditemsdigest (
  id serial,
  md5 char(32) null, 
  sha1 char(40) null,
  categoryname_0 varchar(64) null,
  categoryname_1 varchar(64) null,
  categoryname_2 varchar(64) null,
  categoryname_3 varchar(64) null,
  categoryname_4 varchar(64) null,
  categoryname_5 varchar(64) null,
  categoryname_6 varchar(64) null,
  categoryname_7 varchar(64) null,
  categoryname_8 varchar(64) null,
  categoryname_9 varchar(64) null,
  PRIMARY KEY (id)
);

create index cid_md5_ix on categorizeditemsdigest(md5);
create index cid_sha1_ix on categorizeditemsdigest(sha1);

-- Tables of the structure below should be generated by DSM as metadata is added
-- Don't forget to add digestresult_x (x in 0..9) to dsm.conf !

--create table rowdigestresult_0 (
--  id serial,
--  metadataid integer not null,
--  categoryname varchar(64),
--  PRIMARY KEY (id)
--);


--categorydefinitions defines individual classification system legislation combinations.
--There may be different clasification systems used within a particular legislation, or the same
--labeling system may be used between regions with a slightly different legislation that gives
--a slightly different meaning to the labels used.   
create table categorydefinitions (
   categorydefinitionsid serial,
   name varchar(64) NOT NULL,   --Name for the unique source of the labeled data
   description varchar(256),
   country varchar(3) NOT NULL, --It can be relevant to be able to map clasifications to coresponding legeslation.
   UNIQUE (name,country),       --The name only needs to be unique within the country. For example DE,NATPOL and NL,NATPOL
                                --are allowed to co-excist.
   PRIMARY KEY (categorydefinitionsid)
);

--categorytable defines individual clasification labels within a labeling system used by a specific source.
create table categorytable (
  categoryid serial,
  categorydefinitionsid integer references categorydefinitions(categorydefinitionsid),
  name varchar(64) NOT NULL, --The label of the clasification.
  description varchar(256),
  colorcode varchar(16),     --The color code as used by netclean.
  UNIQUE (categorydefinitionsid,name), --A label only needt to be unique within a clasification system.
  PRIMARY KEY (categoryid)
);


--hashset defines the individual hash pairs with a specific label. 
create table hashset (
 md5 varchar(32),
 sha1 varchar(40),
 categoryid integer references categorytable(categoryid),
 PRIMARY KEY (sha1,md5,categoryid),
 UNIQUE (md5,categoryid),
 UNIQUE (sha1,categoryid)	
);

